
name: nekosama_hive
description: Unofficial dart api for neko-sama.fr with Hive powered search.
version: 2.4.0
homepage: https://github.com/zkayia/nekosama_dart
issue_tracker: https://github.com/zkayia/nekosama_dart/issues
repository: https://github.com/zkayia/nekosama_dart

publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  hive: ^2.2.3
  nekosama:
    git:
      url: https://github.com/zkayia/nekosama_dart
      path: packages/nekosama

dev_dependencies:
  dart_code_metrics: ^5.6.0
